name: Deploy To Production
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20.18.1"
      DEPLOY_PATH: "/home/kevinshaughnessy89/app"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: After Checkout
        run: |
          echo "Current directory"
          pwd
          echo "All files"
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create .ENV File
        run: |
          touch .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "ALPHA_VANTAGE_KEY=${{ secrets.ALPHA_VANTAGE_KEY }}" >> .env
          echo "RSS_KEY=${{ secrets.RSS_KEY }}" >> .env
          echo "REACT_APP_ENV=production" >> .env
          echo "CLIENT_URL=https://kevinshaughnessy.ca" >> .env

      - name: Build Application
        run: yarn build

      - name: Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy To VM
        run: |
          echo "Setting production folder permission to service account user"
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} --command="
            sudo chown -R sa_107039506943432980720 /home/sa_107039506943432980720/production
            chmod -R u+w /home/sa_107039506943432980720/production
          "
          echo "Copying files to server..."
          gcloud compute scp --recurse \
            src/ build/ craco.config.cjs package.json public/ tailwind.config.js tsconfig.json yarn.lock \
            ${{ secrets.VM_NAME }}:/home/sa_107039506943432980720/production --zone=${{ secrets.ZONE }}
          echo "Copying complete."
          echo "Installing dependencies if needed..."
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} --command="
            cd /home/sa_107039506943432980720/production && \
            sudo yarn install --frozen-lockfile --production
          "
          echo "Installation complete."
          echo "Restarting server..."
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} --command="
            cd /home/sa_107039506943432980720/production/src/server && sudo pm2 restart server
          "
          echo "Done."
